# Static TV show dataset for MVP portfolio project.
# Data only — no logic, no filtering, no user input handling.

SHOWS = [
    {
        "title": "Stranger Things",
        "recommendation_reason": None,
        "genres": ["sci-fi", "drama", "mystery"],
        "short_summary": "A group of kids uncover supernatural mysteries in their small town during the 1980s.",
        "content_rating": "TV-14",
        "average_episode_length": 55,
        "number_of_seasons": 4,
        "language": "English",
    },
    {
        "title": "Brooklyn Nine-Nine",
        "recommendation_reason": None,
        "genres": ["comedy", "crime"],
        "short_summary": "A lighthearted comedy following detectives in a New York City police precinct.",
        "content_rating": "TV-14",
        "average_episode_length": 22,
        "number_of_seasons": 8,
        "language": "English",
    },
    {
        "title": "Planet Earth",
        "recommendation_reason": None,
        "genres": ["documentary", "nature"],
        "short_summary": "A visually stunning documentary series exploring Earth's natural wonders.",
        "content_rating": "TV-G",
        "average_episode_length": 50,
        "number_of_seasons": 1,
        "language": "English",
    },
    {
        "title": "The Office",
        "recommendation_reason": None,
        "genres": ["comedy"],
        "short_summary": "A mockumentary-style comedy about everyday office life and awkward coworkers.",
        "content_rating": "TV-14",
        "average_episode_length": 22,
        "number_of_seasons": 9,
        "language": "English",
    },
    {
        "title": "Avatar: The Last Airbender",
        "recommendation_reason": None,
        "genres": ["animation", "adventure", "fantasy"],
        "short_summary": "A young hero must master the elements to restore balance to a war-torn world.",
        "content_rating": "TV-Y7",
        "average_episode_length": 23,
        "number_of_seasons": 3,
        "language": "English",
    },
    {
        "title": "Bluey",
        "recommendation_reason": None,
        "genres": ["animation", "family", "comedy"],
        "short_summary": "A playful family series where everyday moments become imaginative adventures.",
        "content_rating": "TV-Y",
        "average_episode_length": 8,
        "number_of_seasons": 3,
        "language": "English",
    },
    {
        "title": "Modern Family",
        "recommendation_reason": None,
        "genres": ["comedy", "family", "sitcom"],
        "short_summary": "Three connected families navigate parenting, careers, and chaos with humor.",
        "content_rating": "TV-PG",
        "average_episode_length": 22,
        "number_of_seasons": 11,
        "language": "English",
    },
    {
        "title": "Young Sheldon",
        "recommendation_reason": None,
        "genres": ["comedy", "family", "sitcom"],
        "short_summary": "A gifted kid grows up in Texas while his family adapts to his quirks.",
        "content_rating": "TV-PG",
        "average_episode_length": 22,
        "number_of_seasons": 7,
        "language": "English",
    },
    {
        "title": "One Day at a Time",
        "recommendation_reason": None,
        "genres": ["comedy", "family", "sitcom"],
        "short_summary": "A close-knit family balances culture, love, and everyday challenges.",
        "content_rating": "TV-PG",
        "average_episode_length": 30,
        "number_of_seasons": 4,
        "language": "English",
    },
    {
        "title": "The Good Place",
        "recommendation_reason": None,
        "genres": ["comedy", "fantasy", "philosophy"],
        "short_summary": "A woman in the afterlife tries to become a better person.",
        "content_rating": "TV-14",
        "average_episode_length": 22,
        "number_of_seasons": 4,
        "language": "English",
    },
    {
        "title": "The Crown",
        "recommendation_reason": None,
        "genres": ["drama", "historical"],
        "short_summary": "A prestige drama following the British monarchy through major decades.",
        "content_rating": "TV-MA",
        "average_episode_length": 58,
        "number_of_seasons": 6,
        "language": "English",
    },
    {
        "title": "Sherlock",
        "recommendation_reason": None,
        "genres": ["mystery", "crime", "drama"],
        "short_summary": "A modern detective duo solves complex cases in London.",
        "content_rating": "TV-14",
        "average_episode_length": 88,
        "number_of_seasons": 4,
        "language": "English",
    },
    {
        "title": "Breaking Bad",
        "recommendation_reason": None,
        "genres": ["crime", "drama", "thriller"],
        "short_summary": "A chemistry teacher enters the drug trade and transforms dangerously.",
        "content_rating": "TV-MA",
        "average_episode_length": 47,
        "number_of_seasons": 5,
        "language": "English",
    },
    {
        "title": "Better Call Saul",
        "recommendation_reason": None,
        "genres": ["crime", "drama", "legal"],
        "short_summary": "A struggling lawyer gradually becomes a morally compromised fixer.",
        "content_rating": "TV-MA",
        "average_episode_length": 50,
        "number_of_seasons": 6,
        "language": "English",
    },
    {
        "title": "The Good Doctor",
        "recommendation_reason": None,
        "genres": ["drama", "medical"],
        "short_summary": "A talented young surgeon proves himself in a demanding hospital.",
        "content_rating": "TV-14",
        "average_episode_length": 43,
        "number_of_seasons": 7,
        "language": "English",
    },
    {
        "title": "Greys Anatomy",
        "recommendation_reason": None,
        "genres": ["drama", "medical", "romance"],
        "short_summary": "Doctors manage high-pressure emergencies and complicated relationships.",
        "content_rating": "TV-14",
        "average_episode_length": 43,
        "number_of_seasons": 20,
        "language": "English",
    },
    {
        "title": "The Mandalorian",
        "recommendation_reason": None,
        "genres": ["action", "adventure", "sci-fi"],
        "short_summary": "A lone bounty hunter protects a mysterious child across the galaxy.",
        "content_rating": "TV-14",
        "average_episode_length": 40,
        "number_of_seasons": 3,
        "language": "English",
    },
    {
        "title": "Arcane",
        "recommendation_reason": None,
        "genres": ["animation", "action", "fantasy"],
        "short_summary": "Two sisters are pulled into conflict between rival cities.",
        "content_rating": "TV-14",
        "average_episode_length": 41,
        "number_of_seasons": 2,
        "language": "English",
    },
    {
        "title": "Cobra Kai",
        "recommendation_reason": None,
        "genres": ["action", "comedy", "drama"],
        "short_summary": "Old rivals reopen a dojo and reignite long-running tensions.",
        "content_rating": "TV-14",
        "average_episode_length": 30,
        "number_of_seasons": 6,
        "language": "English",
    },
    {
        "title": "Vikings",
        "recommendation_reason": None,
        "genres": ["action", "historical", "drama"],
        "short_summary": "Norse warriors seek power, land, and legacy through brutal campaigns.",
        "content_rating": "TV-MA",
        "average_episode_length": 45,
        "number_of_seasons": 6,
        "language": "English",
    },
    {
        "title": "Chernobyl",
        "recommendation_reason": None,
        "genres": ["historical", "drama", "thriller"],
        "short_summary": "A tense retelling of the nuclear disaster and its aftermath.",
        "content_rating": "TV-MA",
        "average_episode_length": 66,
        "number_of_seasons": 1,
        "language": "English",
    },
    {
        "title": "Our Planet",
        "recommendation_reason": None,
        "genres": ["documentary", "nature", "travel"],
        "short_summary": "A sweeping nature series focused on wildlife and fragile ecosystems.",
        "content_rating": "TV-G",
        "average_episode_length": 50,
        "number_of_seasons": 2,
        "language": "English",
    },
    {
        "title": "Cosmos",
        "recommendation_reason": None,
        "genres": ["documentary", "science"],
        "short_summary": "An accessible exploration of space, science, and human curiosity.",
        "content_rating": "TV-PG",
        "average_episode_length": 44,
        "number_of_seasons": 2,
        "language": "English",
    },
    {
        "title": "MythBusters",
        "recommendation_reason": None,
        "genres": ["documentary", "reality", "science"],
        "short_summary": "Hosts test popular myths using creative experiments and stunts.",
        "content_rating": "TV-PG",
        "average_episode_length": 43,
        "number_of_seasons": 14,
        "language": "English",
    },
    {
        "title": "Survivor",
        "recommendation_reason": None,
        "genres": ["reality", "competition", "survival"],
        "short_summary": "Contestants outwit and outlast each other on remote islands.",
        "content_rating": "TV-PG",
        "average_episode_length": 43,
        "number_of_seasons": 45,
        "language": "English",
    },
    {
        "title": "Alone",
        "recommendation_reason": None,
        "genres": ["reality", "survival", "competition"],
        "short_summary": "Participants survive isolated wilderness conditions with minimal supplies.",
        "content_rating": "TV-14",
        "average_episode_length": 45,
        "number_of_seasons": 10,
        "language": "English",
    },
    {
        "title": "Project Runway",
        "recommendation_reason": None,
        "genres": ["reality", "competition", "design"],
        "short_summary": "Fashion designers compete in themed creative challenges.",
        "content_rating": "TV-PG",
        "average_episode_length": 43,
        "number_of_seasons": 20,
        "language": "English",
    },
    {
        "title": "Chefs Table",
        "recommendation_reason": None,
        "genres": ["documentary", "cooking", "culture"],
        "short_summary": "Each episode profiles a chef and their culinary philosophy.",
        "content_rating": "TV-14",
        "average_episode_length": 50,
        "number_of_seasons": 7,
        "language": "English",
    },
    {
        "title": "The Great British Bake Off",
        "recommendation_reason": None,
        "genres": ["reality", "competition", "cooking"],
        "short_summary": "Home bakers face friendly weekly challenges under a tent.",
        "content_rating": "TV-PG",
        "average_episode_length": 60,
        "number_of_seasons": 14,
        "language": "English",
    },
    {
        "title": "Somebody Feed Phil",
        "recommendation_reason": None,
        "genres": ["travel", "culture", "food"],
        "short_summary": "A cheerful host explores cities through local food and stories.",
        "content_rating": "TV-PG",
        "average_episode_length": 50,
        "number_of_seasons": 7,
        "language": "English",
    },
    {
        "title": "Tiny House Nation",
        "recommendation_reason": None,
        "genres": ["lifestyle", "design", "reality"],
        "short_summary": "Builders help families design compact homes with smart layouts.",
        "content_rating": "TV-PG",
        "average_episode_length": 42,
        "number_of_seasons": 5,
        "language": "English",
    },
    {
        "title": "Anne with an E",
        "recommendation_reason": None,
        "genres": ["drama", "family", "historical"],
        "short_summary": "An imaginative orphan finds belonging in a small rural town.",
        "content_rating": "TV-PG",
        "average_episode_length": 45,
        "number_of_seasons": 3,
        "language": "English",
    },
    {
        "title": "Heartstopper",
        "recommendation_reason": None,
        "genres": ["romance", "drama", "family"],
        "short_summary": "Two teens discover friendship, identity, and first love.",
        "content_rating": "TV-14",
        "average_episode_length": 30,
        "number_of_seasons": 3,
        "language": "English",
    },
    {
        "title": "Money Heist",
        "recommendation_reason": None,
        "genres": ["crime", "thriller", "drama"],
        "short_summary": "A mastermind leads high-stakes heists against major institutions.",
        "content_rating": "TV-MA",
        "average_episode_length": 50,
        "number_of_seasons": 5,
        "language": "Spanish",
    },
    {
        "title": "Elite",
        "recommendation_reason": None,
        "genres": ["thriller", "drama", "crime"],
        "short_summary": "Class tensions and secrets escalate at an elite private school.",
        "content_rating": "TV-MA",
        "average_episode_length": 50,
        "number_of_seasons": 8,
        "language": "Spanish",
    },
    {
        "title": "Lupin",
        "recommendation_reason": None,
        "genres": ["crime", "mystery", "thriller"],
        "short_summary": "A gentleman thief uses clever plans to seek justice.",
        "content_rating": "TV-14",
        "average_episode_length": 45,
        "number_of_seasons": 3,
        "language": "French",
    },
    {
        "title": "Call My Agent",
        "recommendation_reason": None,
        "genres": ["comedy", "drama", "celebrity"],
        "short_summary": "Talent agents juggle demanding clients and personal drama.",
        "content_rating": "TV-14",
        "average_episode_length": 52,
        "number_of_seasons": 4,
        "language": "French",
    },
    {
        "title": "Dark",
        "recommendation_reason": None,
        "genres": ["sci-fi", "thriller", "drama"],
        "short_summary": "A complex time-travel mystery connecting families across generations in a German town.",
        "content_rating": "TV-MA",
        "average_episode_length": 60,
        "number_of_seasons": 3,
        "language": "German",
    },
    {
        "title": "Borgen",
        "recommendation_reason": None,
        "genres": ["drama", "political"],
        "short_summary": "A principled politician navigates power, media, and family pressure.",
        "content_rating": "TV-14",
        "average_episode_length": 58,
        "number_of_seasons": 4,
        "language": "Danish",
    },
    {
        "title": "Squid Game",
        "recommendation_reason": None,
        "genres": ["thriller", "drama", "survival"],
        "short_summary": "Debt-ridden players enter lethal games for a life-changing prize.",
        "content_rating": "TV-MA",
        "average_episode_length": 55,
        "number_of_seasons": 2,
        "language": "Korean",
    },
    {
        "title": "Extraordinary Attorney Woo",
        "recommendation_reason": None,
        "genres": ["legal", "drama", "comedy"],
        "short_summary": "A brilliant young lawyer tackles unusual cases with fresh insight.",
        "content_rating": "TV-14",
        "average_episode_length": 70,
        "number_of_seasons": 1,
        "language": "Korean",
    },
    {
        "title": "Crash Landing on You",
        "recommendation_reason": None,
        "genres": ["romance", "drama", "comedy"],
        "short_summary": "An heiress and an officer form a risky cross-border romance.",
        "content_rating": "TV-14",
        "average_episode_length": 75,
        "number_of_seasons": 1,
        "language": "Korean",
    },
    {
        "title": "Kingdom",
        "recommendation_reason": None,
        "genres": ["horror", "thriller", "historical"],
        "short_summary": "A crown prince faces political schemes and a spreading plague.",
        "content_rating": "TV-MA",
        "average_episode_length": 50,
        "number_of_seasons": 2,
        "language": "Korean",
    },
    {
        "title": "Sacred Games",
        "recommendation_reason": None,
        "genres": ["crime", "thriller", "drama"],
        "short_summary": "A troubled cop races to stop a catastrophic citywide threat.",
        "content_rating": "TV-MA",
        "average_episode_length": 50,
        "number_of_seasons": 2,
        "language": "Hindi",
    },
    {
        "title": "Delhi Crime",
        "recommendation_reason": None,
        "genres": ["crime", "drama", "true crime"],
        "short_summary": "Police investigators pursue justice in difficult real-world cases.",
        "content_rating": "TV-MA",
        "average_episode_length": 45,
        "number_of_seasons": 2,
        "language": "Hindi",
    },
    {
        "title": "Erased",
        "recommendation_reason": None,
        "genres": ["mystery", "thriller", "psychological"],
        "short_summary": "A man relives childhood events to prevent a chain of crimes.",
        "content_rating": "TV-14",
        "average_episode_length": 28,
        "number_of_seasons": 1,
        "language": "Japanese",
    },
    {
        "title": "Midnight Diner",
        "recommendation_reason": None,
        "genres": ["slice of life", "drama", "food"],
        "short_summary": "Late-night diners share stories at a small neighborhood restaurant.",
        "content_rating": "TV-14",
        "average_episode_length": 24,
        "number_of_seasons": 3,
        "language": "Japanese",
    },
    {
        "title": "Alice in Borderland",
        "recommendation_reason": None,
        "genres": ["sci-fi", "thriller", "survival"],
        "short_summary": "Friends are trapped in a deadly alternate Tokyo of game trials.",
        "content_rating": "TV-MA",
        "average_episode_length": 50,
        "number_of_seasons": 2,
        "language": "Japanese",
    },
    {
        "title": "3 Percent",
        "recommendation_reason": None,
        "genres": ["sci-fi", "thriller", "drama"],
        "short_summary": "Young adults compete in harsh tests for a chance at privilege.",
        "content_rating": "TV-MA",
        "average_episode_length": 45,
        "number_of_seasons": 4,
        "language": "Portuguese",
    },
    {
        "title": "The Hook Up Plan",
        "recommendation_reason": None,
        "genres": ["romance", "comedy"],
        "short_summary": "Friends stage a dating plan that quickly becomes complicated.",
        "content_rating": "TV-MA",
        "average_episode_length": 30,
        "number_of_seasons": 3,
        "language": "French",
    },
]


def get_all_shows():
    """Return the full static list of TV shows."""
    return SHOWS
